from enum import Enum, auto


class LexemeType(Enum):
    SPACE = auto()
    KEYWORD = auto()
    PROCEDURE = auto()
    IDENTIFIER = auto()
    VARIABLE = auto()
    OBJECT = auto()
    CLASS = auto()
    SUB = auto()
    FUNCTION = auto()
    PROPERTY_GET = auto()
    PROPERTY_LET = auto()
    PROPERTY_SET = auto()
    PAREN_BEGIN = auto()
    PAREN_END = auto()
    COMMA = auto()
    STRING = auto()
    DATE = auto()
    INTEGER = auto()
    REAL = auto()
    SPECIAL_VALUE = auto()
    SPECIAL_OBJECT = auto()
    DOT = auto()
    OPERATOR = auto()
    COMMENT = auto()
    LINE_CONT = auto()
    STATEMENT_CONCAT = auto()
    NEWLINE = auto()


class TokenType(Enum):
    INIT = auto()
    SPACE = auto()
    LEXEME = auto()
    PAREN_BEGIN = auto()
    PAREN_END = auto()
    COMMA = auto()
    LITERAL_STRING = auto()
    LITERAL_INTEGER = auto()
    LITERAL_DATE = auto()
    DOT = auto()
    OPERATOR = auto()
    COMMENT = auto()
    LINE_CONT = auto()
    STATEMENT_CONCAT = auto()
    NEWLINE = auto()
